---

# Provision our AWS Instances:

- hosts: all
  become: yes
  gather_facts: yes


  tasks:
  - name: base provisioning
    include_role:
      name: aws

  - name: include zen_cloud role for webserver node(s)
    include_role:
      name: zen_cloud
    when: system_role == "webserver"

  - name: include zen_db role for database node(s)
    include_role:
      name: zen_db
    tags:
      - all
      - initdb
    when: system_role == "dbserver"
